services:
  - type: web
    name: empai-chatbot
    env: python
    plan: free
    region: oregon  # or virginia if that's what you selected
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    runtime: python3
    autoDeploy: true
    envVars:
      - key: EXCEL_FILE_PATH
        value: EMPLOYEE MANAGEMENT.xlsx
